---
dependency:
  name: galaxy
  options:
    role-file: integration_requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: ubuntu
    box: ubuntu/bionic64
    memory: 512
    cpus: 1
    provider_raw_config_args:
    - "customize [ 'modifyvm', :id, '--uartmode1', 'disconnected' ]"
  - name: epicRaspberries
    box: Bassualdo/rpd-amd64-buster
    instance_raw_config_args:
      - "ssh.username = 'pi'"
      - "ssh.password = 'raspberry'"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x:
        - 401  # Git checkouts must contain explicit version
verifier:
  name: goss
  lint:
    name: yamllint
