---

- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/7/x86_64/

- name: install os packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - nodejs
    - which
    - curl

- name: Download nodered setup script
  get_url:
    url: https://raw.githubusercontent.com/node-red/linux-installers/master/rpm/update-nodejs-and-nodered
    dest: /tmp/
    mode: 0755
  register: nodered

- name: install node-red service
  copy:
    src: 'Node-RED.service'
    dest: '/etc/systemd/system/'
  notify:
    - force systemd to reread configs
    - start node-red and configure autostart at boot
