---
- name: install git
  apt:
    name:
      - git
      - curl
    state: present

- name: execute nodered setup script
  shell: >
    set -o pipefail && \
    curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  args:
    warn: false
    executable: /bin/bash
  changed_when: false

- name: install nodejs os package
  yum:
    name:
      - nodejs
    state: present

- name: Install "node-red" node.js package. Takes a few minutes!
  npm:
    name: node-red
    unsafe_perm: true
    global: true

# - name: Install node-red-contrib-ttn node.js package. Takes a few minutes!
#   npm:
#     name: node-red-contrib-ttn
#   become: yes
