---
- name: uninstall eventually by os distribution installed nodered version
  apt:
    name:
      - nodered
    state: absent

- name: install os packages
  apt:
    name:
      - git
      - nodejs
      - curl
    state: present

- name: Download nodered setup script
  get_url:
    url: https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered
    dest: /tmp/
    mode: 0755
  register: nodered

- name: configure to start node-red as root - needs do be changed for production use
  lineinfile:
    path: /lib/systemd/system/nodered.service
    regexp: '^User='
    line: User=root
  notify:
    - force systemd to reread configs
    - start node-red and configure autostart at boot
