---
- name: uninstall eventually by os distribution installed nodered version
  apt:
    name:
      - nodered
    state: absent

- name: install os packages
  apt:
    name:
      - git
      - nodejs
      - curl
    state: installed

- name: Download nodered setup script
  get_url:
    url: https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered
    dest: /tmp/
    mode: 0755
  register: nodered
