---
- name: install git
  apt:
    name: 'git'
    state: present

- name: Download nodered setup script
  get_url:
    url: https://deb.nodesource.com/setup_8.x
    dest: ~/
    mode: 0755
  notify: configure for nodejs installation

- name: install nodejs os package
  yum:
    name:
      - nodejs
      - npm
    state: present

- name: Install "node-red" node.js package. Takes a few minutes!
  npm:
    name: node-red
    unsafe_perm: true
    global: true

# - name: Install node-red-contrib-ttn node.js package. Takes a few minutes!
#   npm:
#     name: node-red-contrib-ttn
#   become: yes
