---
- name: install os packages
  apt:
    name:
      - git
      - curl
      - apt-transport-https
    state: present

- name: install gpg key for nodesource repo
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: add nodesource repository
  apt_repository:
    repo: 'deb https://deb.nodesource.com/{{ nodejs_repo }} {{ ansible_distribution_release }} main'
    state: present

- name: uninstall eventually by os distribution installed nodered version
  apt:
    name:
      - nodered
    state: absent

- name: install nodejs
  apt:
    name:
      - nodejs
    update_cache: true
    state: latest

# - name: Download nodered setup script
#   get_url:
#     url: https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered
#     dest: /tmp/
#     mode: 0755
#   register: nodered
