---

- debug:
    msg: Playbook running against {{ ansible_os_family }} release {{ ansible_distribution_release }}

- name: include tasks for RedHat OS Family
  include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: include tasks for Debian Stretch
  include_tasks: debian-stretch.yml
  when: ansible_os_family == "Debian" and ansible_distribution_release == 'stretch'

- name: include tasks for Debian Buster
  include_tasks: debian.yml
  when: ansible_os_family == "Debian" and ansible_distribution_release == 'buster'

- name: include tasks for Ubuntu Bionic
  include_tasks: debian.yml
  when: ansible_os_family == "Debian" and ansible_distribution_release == 'bionic'


- name: Install node-red
  npm:
    name: node-red
    unsafe_perm: true
    global: true

- name: Install node-red-admin
  npm:
    name: node-red-admin
    global: true

- name: Install node-red-contrib-mongodb3
  npm:
    name: node-red-admin
    global: true

- name: install node-red service
  copy:
    src: 'nodered.service'
    dest: '/lib/systemd/system/nodered.service'
    force: false
  notify:
    - force systemd to reread configs
    - start node-red and configure autostart at boot

- name: configure to start node-red as root - needs do be changed for production use
  lineinfile:
    path: /lib/systemd/system/nodered.service
    regexp: '^User='
    line: User=root
  notify:
    - force systemd to reread configs
    - start node-red and configure autostart at boot
