---

- include_tasks: centOS.yml
  when: ansible_os_family == "RedHat"

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: configure for nodejs installation
  shell: 'yes | bash /tmp/update-nodejs-and-nodered'
  when: nodered is defined and nodered.changed

- name: Install "node-red" node.js package. Takes a few minutes!
  npm:
    name: node-red
    unsafe_perm: true
    global: true

- name: Install node-red-contrib-ttn node.js package. Takes a few minutes!
  npm:
    name: node-red-contrib-ttn
    path: /root/.node-red/

- name: start node-red as root
  lineinfile:
    path: /lib/systemd/system/nodered.service
    regexp: '^User='
    line: User=root
  notify: force systemd to reread configs

- name: Make sure node-red is started and enabled to start on boot
  systemd:
    name: 'nodered'
    state: 'started'
    enabled: true
