---

- include_tasks: centOS.yml
  when: ansible_os_family == "RedHat"

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Install node-red
  npm:
    name: node-red
    unsafe_perm: true
    global: true

- name: install node-red service
  copy:
    src: 'nodered.service'
    dest: '/lib/systemd/system/nodered.service'
    force: false
  notify:
    - force systemd to reread configs
    - start node-red and configure autostart at boot

- name: configure to start node-red as root - needs do be changed for production use
  lineinfile:
    path: /lib/systemd/system/nodered.service
    regexp: '^User='
    line: User=root
  notify:
    - force systemd to reread configs
    - start node-red and configure autostart at boot
