---

- include_tasks: centOS.yml
  when: ansible_os_family == "RedHat"

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: install node-red service
  copy:
    src: 'Node-RED.service'
    dest: '/etc/systemd/system/'
  notify:
    - 'daemon reload'
    - 'service start'
