---

- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/7/x86_64/

- name: install os packages
  yum:
    name:
      - git
      - nodejs
      - npm
      - which
      - curl
    state: present
