---

- name: configure for nodejs installation
  command: ~/setup_8.x

- name: daemon reload
  systemd:
    state: started
    daemon_reload: true
    name: Node-RED
- name: service start
  service:
    name: 'Node-RED'
    state: 'started'
    enabled: 'yes'
