---

- name: prepare nodejs installation
  command: '~/setup_{{ node_version }}.x'

- name: daemon reload
  systemd:
    state: started
    daemon_reload: true
    name: Node-RED
- name: service start
  service:
    name: 'Node-RED'
    state: 'started'
    enabled: 'yes'
