---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    # image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian10}-ansible:latest"
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu1804}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x:
        - 503  # task when changed allowed no handler needed-
        - 306  # ignore pipefail for pipes. Testing
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
